### PR TITLE
Add datacenter label for metrics exposed

### PR DESCRIPTION
**Pull request by geobeau**
This PR add the label datacenter as given by Cassandra on all the metrics.

### CODE REVIEW

**Comment by erebe** [comment]
Missing a file I guess

**Comment by ashangit** [comment]
why do we need this? don't we rely on the dc tag from consul?

**Comment by deimosfr** [comment]
> why do we need this? don't we rely on the dc tag from consul?

Because 42

**Comment by geobeau** [comment]
No, it can be different. You can have two "cassandra datacenter" in the same "consul datacenter" during a migration for exemple. They can also follow different naming convention

**Review by ashangit — APPROVED** [review]

**Comment by erebe** [comment]
Be sure to check that the prometheus rules are still valid after that

**Pull request merged**
